etude_variable::analyse
def etude_variable.analyse.Print_confusion_matrix
def etude_variable.analyse.Report_scores
Referenced by etude_variable.analyse.my_fit.
def etude_variable.analyse.my_randomize_estimateur
Referenced by etude_variable.analyse.my_fit.
def etude_variable.analyse.my_randomize_estimateur2
Referenced by etude_variable.analyse.my_fit2.
def etude_variable.analyse.CorrelationDesVariable
References etude_variable.analyse.split_dataset.
def etude_variable.analyse.split_dataset
References etude_variable.analyse.Plot_learning_curve.
Referenced by etude_variable.analyse.CorrelationDesVariable, etude_variable.analyse.my_split, etude_variable.analyse.my_split_XBOOST.
def etude_variable.analyse.Plot_learning_curve
Referenced by etude_variable.analyse.split_dataset.
def etude_variable.analyse.Plot_predictor_importance
def etude_variable.analyse.my_split
References etude_variable.analyse.my_split_XBOOST, etude_variable.analyse.split_dataset.
def etude_variable.analyse.my_split_XBOOST
References etude_variable.analyse.split_dataset.
Referenced by etude_variable.analyse.my_split.
def etude_variable.analyse.run_randomsearch
Run a random search for best Decision Tree parameters. Args ---- X -- features y -- targets (classes) cf -- scikit-learn Decision Tree param_dist -- [dict] list, distributions of parameters to sample cv -- fold of cross-validation, default 5 n_iter_search -- number of random parameter sets to try, default 20. Returns ------- top_params -- [dict] from report()
References etude_variable.analyse.report2.
def etude_variable.analyse.report2
Report top n_top parameters settings, default n_top=3. Args ---- grid_scores -- output from grid or random search n_top -- how many to report, of top models Returns ------- top_params -- [dict] top parameter settings found in search
References etude_variable.analyse.my_fit2.
Referenced by etude_variable.analyse.run_gridsearch, etude_variable.analyse.run_randomsearch.
def etude_variable.analyse.my_fit2
References etude_variable.analyse.my_fit, etude_variable.analyse.my_randomize_estimateur2.
Referenced by etude_variable.analyse.report2.
def etude_variable.analyse.my_fit
References etude_variable.analyse.afficheEvalSet, etude_variable.analyse.my_randomize_estimateur, etude_variable.analyse.Report_scores.
Referenced by etude_variable.analyse.my_fit2.
def etude_variable.analyse.afficheEvalSet
References etude_variable.analyse.evaluation.
Referenced by etude_variable.analyse.evaluation, etude_variable.analyse.my_fit.
def etude_variable.analyse.evaluation
References etude_variable.analyse.afficheEvalSet.
Referenced by etude_variable.analyse.afficheEvalSet.
def etude_variable.analyse.my_crossValidation
def etude_variable.analyse.run_gridsearch
Run a grid search for best Decision Tree parameters. Args ---- X -- features y -- targets (classes) cf -- scikit-learn Decision Tree param_grid -- [dict] parameter settings to test cv -- fold of cross-validation, default 5 Returns ------- top_params -- [dict] from report()
References etude_variable.analyse.report2.